export const sidebar = [
  {
    label: 'Overview',
    color: 'text-[#FFCB6B]',
    icon: 'TbFileFilled',
  },
  {
    label: 'Javascript Basics',
    icon: 'TbTriangleSquareCircle',
    color: 'text-[#C3E88D]',
    children: [
      'Introduction',
      'Variables',
      'Booleans',
      'Arithmetic Operators',
      'Strings',
      'Arrays',
      'Objects',
    ],
  },
  {
    label: 'Control Flow',
    icon: 'TbArrowLeftRight',
    color: 'text-[#89DDFF]',
    children: [
      'Conditionals',
      'Comparison Operators',
      'Logical Operators',
      'Switch Statements',
      'Exception Handling',
    ],
  },
  {
    label: 'Loops',
    icon: 'TbExchange',
    color: 'text-[#C792EA]',
    children: [
      'for Loop',
      'while Loop',
      'do-while Loop',
      'Nested Loops',
      'Control Statements',
    ],
  },
  {
    label: 'Functions',
    icon: 'TbSchema',
    color: 'text-[#FF5370]',
    children: [
      'Introduction',
      'Parameters',
      'Function Scope',
      'Arrow Functions',
      'Closures',
    ],
  },
  {
    label: 'Arrays',
    icon: 'TbBracketsContain',
    color: 'text-[#FFCB6B]',
    children: [
      'Introduction',
      'Array Methods',
    ],
  },
  {
    label: 'Objects',
    icon: 'TbCodeDots',
    color: 'text-[#C3E88D]',
    children: [
      'Introduction',
      'Properties',
      'Constructors',
      'Prototypes',
      'ES6 Classes',
    ],
  },
  {
    label: 'Asynchronous JS',
    icon: 'TbVectorBezier',
    color: 'text-[#89DDFF]',
    children: [
      'Introduction',
      'Callback Functions',
      'Promises',
      'Async / Await',
      'Fetch API',
      'Error Handling',
    ],
  },
  {
    label: 'Javascript DOM',
    icon: 'TbSitemap',
    color: 'text-[#C792EA]',
    children: [
      'Introduction',
      'Accessing DOM Elements',
      'Modifying DOM Elements',
      'DOM Traversal',
      'Event Handling',
      'Creating DOM Elements',
    ],
  },
];

